export const ACHIEVEMENTS = [
  {
    nom: "Welcome on board",
    description: "Congrats ! You found your first pirate coin",
    type: "totalscore",
    condition: 1,
    url: "./assets2/Gumlins.png",
    announced: false,
  },
  {
    nom: "Welcome on board",
    description: "Congrats You found 1000 coins!",
    type: "totalscore",
    condition: 1000,
    url: "./assets2/SuperGumlins.png",
    announced: false,
  },
  {
    nom: "Welcome on board",
    description: "Congrats You found 100,000 coins!",
    type: "totalscore",
    condition: 100000,
    url: "./assets2/HyperGumlins.png",
    announced: false,
  },
  {
    nom: "Welcome on board",
    description: "Congrats You found 100,000 coins!",
    type: "totalscore",
    condition: 100000000,
    url: "./assets2/HyperGumlins.png",
    announced: false,
  },
  {
    nom: "Welcome on board",
    description: "Congrats You found 100,000 coins!",
    type: "totalscore",
    condition: 100000000000,
    url: "./assets2/HyperGumlins.png",
    announced: false,
  },
];
