export const UPGRADES = [
  {
    name: "SAN'S CHAOTIC MOVES",
    type: "building",
    description:
      "San's hability to dance improves every San's CpS by two percents",
    condition: 10,
    target: 0,
    purchased: false,
    price: 100,
    effect: 1.2,
  },
  {
    name: "HONGJOONG'S CAPTAIN POWER",
    type: "building",
    description:
      "Hongjoong's leadership talent improves every Hongjoong's CpS by two percents",
    condition: 10,
    target: 1,
    purchased: false,
    price: 200,
    effect: 1.2,
  },
  {
    name: "Jongho's Apple breaking Combo",
    type: "building",
    description:
      "Jongho's ability to break apples helps him to find coins faster by two percents",
    condition: 10,
    target: 2,
    purchased: false,
    price: 300,
    effect: 1.2,
  },
  {
    name: "Yeosang's Hehetmon Cuteness",
    type: "building",
    description:
      "Yeosang's cute creature helps you find coins faster by two percents",
    condition: 10,
    target: 3,
    purchased: false,
    price: 400,
    effect: 1.2,
  },
  {
    name: "Yunho's Unrivaled Twerk",
    type: "building",
    condition: 10,
    target: 4,
    purchased: false,
    price: 500,
    effect: 1.2,
  },
  {
    name: "Seonghwas's Baby Sharking",
    type: "building",
    condition: 10,
    target: 5,
    purchased: false,
    price: 600,
    effect: 1.2,
  },
  {
    name: "Mingi's Unequaled Styling",
    type: "building",
    condition: 10,
    target: 6,
    purchased: false,
    price: 700,
    effect: 1.2,
  },
  {
    name: "Wooyoung's Infinite Yelling",
    condition: 10,
    target: 7,
    purchased: false,
    price: 800,
    effect: 1.2,
  },
  {
    name: "Amicus ad Aras",
    type: "building",
    condition: 30,
    target: 0,
    purchased: false,
    price: 1000,
    effect: 1.6,
  },
  {
    name: "Hehet!",
    type: "building",
    condition: 30,
    target: 4,
    purchased: false,
    price: 1000,
    effect: 1.6,
  },
  {
    name: "HalaHala!",
    type: "clickers",
    condition: 30,
    target: 0,
    purchased: false,
    price: 1000,
    effect: 2,
  },
  {
    name: "Aurora",
    type: "CpS",
    condition: 100,
    target: 0,
    purchased: false,
    price: 100,
    effect: 2,
  },
  {
    name: "SAN'S HIPS ARE CRAZY",
    type: "building",
    description:
      "San's ability to move his hips without trouble improves every San's CpS by 50 percents",
    condition: 50,
    target: 0,
    purchased: false,
    price: 100,
    effect: 1.2,
  },
];
